export const GET_PLAYLIST = 'PLAYER/PLAYLIST/GET';
export const PLAY_NEXT = 'PLAYER/PLAYLIST/PLAY/NEXT';
export const ADD_ITEM = 'PLAYER/PLAYLIST/ITEM/ADD';
export const REMOVE_ITEM = 'PLAYER/PLAYLIST/ITEM/REMOVE';